# Copyright (c) 2021 Arm Limited
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and

name: BR-Publish Doxygen Documents
# Branch Test for publish Doxygen documents


on:
  # Triggers the workflow on push, only with header file changed
  push:
    branches: [ main ]
    paths: [ '**/*.h' ]

  # Allows this workflow manually triggered
  workflow_dispatch:


jobs:

  Doxygen:
    runs-on: ubuntu-latest
    # Run this this job inside container
    container: mcudriverhal/ci-build-env:sanity

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git Configurations
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com    

      # generate doxygen html on a Detached HEAD
      - name: Generate new doxygen html
        run: |
          git fetch origin
          git checkout origin/main
          rm -rf ./docs/doxygen/html
          mkdir -p ./docs/doxygen/html
          doxygen ./docs/doxygen/doxyfile_options

      # Create a commit with new html on detached HEAD, then cherry-pick to docs-doxygen_html branch
      - name: Create a commit with new artifacts
        run: |
          MAIN_SHA=$(git rev-parse --short HEAD)
          git add ./docs/doxygen/html
          git commit -m "Doxy: Generate HTML @ $MAIN_SHA"
          git fetch origin
          git checkout origin/docs-doxygen_html
          git cherry-pick --strategy=recursive --strategy-option=theirs HEAD@{1}
          git log --oneline -5

      - name: Push Doxygen branch to remote 
        run: |
          git push origin HEAD:docs-doxygen_html
